# Generated by Django 5.0.6 on 2024-07-01 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_mysite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='account',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
