# Generated by Django 5.0.6 on 2024-07-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_mysite_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysite',
            name='account',
        ),
    ]
